In [56]:
import pandas as pd
import numpy as np

In [57]:
data = pd.read_csv('all_anime.csv')

In [58]:
data

,Unnamed: 0,user_id,anime_id,rating,watching_status,watched_episodes,Name,Tags
0,0,0,7173,0.0,4,0,Haikyuu!! Movie 2: Shousha to Haisha,"Shounen, Sports, Recap, School Club, School Li..."
1,1,0,5323,0.0,2,1,Attack on Titan,"Action, Fantasy, Horror, Shounen, Dark Fantasy..."
2,2,0,5028,0.0,2,5,My Little Monster,"Comedy, Romance, Shoujo, Slice of Life, Opposi..."
3,3,0,1048,0.0,4,0,Death Note,"Mystery, Shounen, Crime, Criminals, Detectives..."
4,4,0,12221,0.0,2,4,Fruits Basket 1st Season,"Comedy, Drama, Fantasy, Romance, Shoujo, Anima..."
...,...,...,...,...,...,...,...,...
20842196,20842196,79300,3999,4.5,1,0,Bakuman. 2,"Drama, Shounen, Anime Industry, Manga Industry..."
20842197,20842197,79300,8535,4.5,1,0,Tsuredure Children,"Comedy, Romance, Shounen, Episodic, Love Confe..."
20842198,20842198,79300,6646,3.0,3,2,Shirobako,"Comedy, Drama, Slice of Life, Anime Industry, ..."
20842199,20842199,79300,5765,4.0,1,0,Fairy Tail 2,"Action, Adventure, Comedy, Fantasy, Shounen, G..."
20842200,20842200,79300,5926,4.5,1,0,The Kawai Complex Guide to Manors and Hostel B...,"Comedy, Romance, Seinen, Slice of Life, Boardi..."

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20842201 entries, 0 to 20842200
Data columns (total 8 columns):
 #   Column            Dtype
---  ------            -----
 0   Unnamed: 0        int64
 1   user_id           int64
 2   anime_id          int64
 3   rating            float64
 4   watching_status   int64
 5   watched_episodes  int64
 6   Name              object
 7   Tags              object
dtypes: float64(1), int64(5), object(2)
memory usage: 1.2+ GB

In [60]:
data.describe()

,Unnamed: 0,user_id,anime_id,rating,watching_status,watched_episodes
count,2.084220e+07,2.084220e+07,2.084220e+07,2.084220e+07,2.084220e+07,2.084220e+07
mean,1.042110e+07,3.984237e+04,4.826288e+03,1.747458e+00,2.436974e+00,1.716115e+00
std,6.016625e+06,2.285348e+04,3.823595e+03,2.005187e+00,1.713224e+00,2.510919e+01
min,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.210550e+06,1.983300e+04,1.549000e+03,0.000000e+00,1.000000e+00,0.000000e+00
50%,1.042110e+07,4.032900e+04,4.207000e+03,0.000000e+00,1.000000e+00,0.000000e+00
75%,1.563165e+07,5.936700e+04,7.123000e+03,4.000000e+00,4.000000e+00,0.000000e+00
max,2.084220e+07,7.930000e+04,1.736500e+04,6.000000e+00,6.000000e+00,2.605000e+03

In [61]:
data.isnull().sum()

Unnamed: 0             0
user_id                0
anime_id               0
rating                 0
watching_status        0
watched_episodes       0
Name                1508
Tags                1508
dtype: int64

In [62]:
data.dropna(inplace=True)

In [63]:
data.isnull().sum()

Unnamed: 0          0
user_id             0
anime_id            0
rating              0
watching_status     0
watched_episodes    0
Name                0
Tags                0
dtype: int64

In [64]:
data.drop_duplicates(inplace=True)

In [65]:
data = data.drop(['Unnamed: 0'], axis=1)

In [66]:
data

,user_id,anime_id,rating,watching_status,watched_episodes,Name,Tags
0,0,7173,0.0,4,0,Haikyuu!! Movie 2: Shousha to Haisha,"Shounen, Sports, Recap, School Club, School Li..."
1,0,5323,0.0,2,1,Attack on Titan,"Action, Fantasy, Horror, Shounen, Dark Fantasy..."
2,0,5028,0.0,2,5,My Little Monster,"Comedy, Romance, Shoujo, Slice of Life, Opposi..."
3,0,1048,0.0,4,0,Death Note,"Mystery, Shounen, Crime, Criminals, Detectives..."
4,0,12221,0.0,2,4,Fruits Basket 1st Season,"Comedy, Drama, Fantasy, Romance, Shoujo, Anima..."
...,...,...,...,...,...,...,...
20842196,79300,3999,4.5,1,0,Bakuman. 2,"Drama, Shounen, Anime Industry, Manga Industry..."
20842197,79300,8535,4.5,1,0,Tsuredure Children,"Comedy, Romance, Shounen, Episodic, Love Confe..."
20842198,79300,6646,3.0,3,2,Shirobako,"Comedy, Drama, Slice of Life, Anime Industry, ..."
20842199,79300,5765,4.0,1,0,Fairy Tail 2,"Action, Adventure, Comedy, Fantasy, Shounen, G..."
20842200,79300,5926,4.5,1,0,The Kawai Complex Guide to Manors and Hostel B...,"Comedy, Romance, Seinen, Slice of Life, Boardi..."

In [67]:
new_feature = ['anime_id', 'user_id', 'Name', 'Tags', 'watching_status', 'watched_episodes', 'rating']

data = data.reindex(columns=new_feature)
data

,anime_id,user_id,Name,Tags,watching_status,watched_episodes,rating
0,7173,0,Haikyuu!! Movie 2: Shousha to Haisha,"Shounen, Sports, Recap, School Club, School Li...",4,0,0.0
1,5323,0,Attack on Titan,"Action, Fantasy, Horror, Shounen, Dark Fantasy...",2,1,0.0
2,5028,0,My Little Monster,"Comedy, Romance, Shoujo, Slice of Life, Opposi...",2,5,0.0
3,1048,0,Death Note,"Mystery, Shounen, Crime, Criminals, Detectives...",4,0,0.0
4,12221,0,Fruits Basket 1st Season,"Comedy, Drama, Fantasy, Romance, Shoujo, Anima...",2,4,0.0
...,...,...,...,...,...,...,...
20842196,3999,79300,Bakuman. 2,"Drama, Shounen, Anime Industry, Manga Industry...",1,0,4.5
20842197,8535,79300,Tsuredure Children,"Comedy, Romance, Shounen, Episodic, Love Confe...",1,0,4.5
20842198,6646,79300,Shirobako,"Comedy, Drama, Slice of Life, Anime Industry, ...",3,2,3.0
20842199,5765,79300,Fairy Tail 2,"Action, Adventure, Comedy, Fantasy, Shounen, G...",1,0,4.0
20842200,5926,79300,The Kawai Complex Guide to Manors and Hostel B...,"Comedy, Romance, Seinen, Slice of Life, Boardi...",1,0,4.5

watching status :
1 : Watched
2 : Watching
3 : Dropped
4 : Want to Watch
5 : Stalled
6 : Wont Watch

In [68]:
data.describe()

,anime_id,user_id,watching_status,watched_episodes,rating
count,2.084069e+07,2.084069e+07,2.084069e+07,2.084069e+07,2.084069e+07
mean,4.825386e+03,3.984177e+04,2.436816e+00,1.716238e+00,1.747571e+00
std,3.822263e+03,2.285367e+04,1.713141e+00,2.511009e+01,2.005204e+00
min,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.549000e+03,1.983300e+04,1.000000e+00,0.000000e+00,0.000000e+00
50%,4.207000e+03,4.032900e+04,1.000000e+00,0.000000e+00,0.000000e+00
75%,7.122000e+03,5.936700e+04,4.000000e+00,0.000000e+00,4.000000e+00
max,1.723100e+04,7.930000e+04,6.000000e+00,2.605000e+03,6.000000e+00

In [69]:
watching_status_sum = (data.watching_status == 0).sum()
watched_episodes_sum = (data.watched_episodes == 0).sum()
rating_sum = (data.rating == 0).sum()

print("watching_status 0 values : ", watching_status_sum)
print("watched_episodes 0 value : ", watched_episodes_sum)
print("rating 0 values : ", rating_sum)

watching_status 0 values :  3258
watched_episodes 0 value :  19173100
rating 0 values :  11148209

In [70]:
data.loc[(data['watching_status'] == 0)]

,anime_id,user_id,Name,Tags,watching_status,watched_episodes,rating
10954,99,32,Dragon Ball,"Action, Adventure, Comedy, Shounen, Journey to...",0,0,1.0
10955,55,32,Hunter x Hunter,"Action, Adventure, Fantasy, Shounen, Martial A...",0,0,1.0
10956,22,32,Naruto,"Action, Drama, Shounen, Japanese Mythology, Ni...",0,0,1.0
10957,172,32,Hajime no Ippo: The Fighting!,"Action, Drama, Shounen, Sports, Boxing, Hand t...",0,0,1.0
10958,3480,32,Infinite Stratos,"Ecchi, Harem, Mecha, Sci Fi, Seinen, All-Girls...",0,0,5.0
...,...,...,...,...,...,...,...
115173,920,438,Dragon Ball Z Movie 9: Bojack Unbound,"Action, Shounen, Aliens, Hand to Hand Combat, ...",0,0,1.0
115174,1367,438,Nanatsuiro Drops,"Fantasy, Magical Girl, Romance, Henshin Heroes...",0,0,4.0
115175,1505,438,Dragon Ball Movie 4: The Path to Power,"Action, Adventure, Shounen, Hand to Hand Comba...",0,0,1.0
117616,10118,448,The Promised Neverland,"Fantasy, Horror, Mystery, Sci Fi, Shounen, Dar...",0,1,2.0
117617,7585,448,My Hero Academia,"Action, Comedy, Drama, Sci Fi, Shounen, School...",0,6,2.0

In [71]:
data.loc[(data['watched_episodes'] == 0)]

,anime_id,user_id,Name,Tags,watching_status,watched_episodes,rating
0,7173,0,Haikyuu!! Movie 2: Shousha to Haisha,"Shounen, Sports, Recap, School Club, School Li...",4,0,0.0
3,1048,0,Death Note,"Mystery, Shounen, Crime, Criminals, Detectives...",4,0,0.0
6,147,0,Fruits Basket,"Comedy, Drama, Fantasy, Romance, Shoujo, Anima...",1,0,5.0
8,3977,0,Future Diary,"Action, Shounen, Battle Royale, High Stakes Ga...",4,0,0.0
9,4685,1,Dusk Maiden of Amnesia,"Mystery, Romance, Shounen, Ghosts, School Club...",2,0,4.0
...,...,...,...,...,...,...,...
20842195,1078,79300,Tengen Toppa Gurren Lagann,"Action, Adventure, Comedy, Mecha, Sci Fi, Comb...",4,0,0.0
20842196,3999,79300,Bakuman. 2,"Drama, Shounen, Anime Industry, Manga Industry...",1,0,4.5
20842197,8535,79300,Tsuredure Children,"Comedy, Romance, Shounen, Episodic, Love Confe...",1,0,4.5
20842199,5765,79300,Fairy Tail 2,"Action, Adventure, Comedy, Fantasy, Shounen, G...",1,0,4.0
20842200,5926,79300,The Kawai Complex Guide to Manors and Hostel B...,"Comedy, Romance, Seinen, Slice of Life, Boardi...",1,0,4.5

In [72]:
data.loc[(data['rating'] == 0)]

,anime_id,user_id,Name,Tags,watching_status,watched_episodes,rating
0,7173,0,Haikyuu!! Movie 2: Shousha to Haisha,"Shounen, Sports, Recap, School Club, School Li...",4,0,0.0
1,5323,0,Attack on Titan,"Action, Fantasy, Horror, Shounen, Dark Fantasy...",2,1,0.0
2,5028,0,My Little Monster,"Comedy, Romance, Shoujo, Slice of Life, Opposi...",2,5,0.0
3,1048,0,Death Note,"Mystery, Shounen, Crime, Criminals, Detectives...",4,0,0.0
4,12221,0,Fruits Basket 1st Season,"Comedy, Drama, Fantasy, Romance, Shoujo, Anima...",2,4,0.0
...,...,...,...,...,...,...,...
20842169,3347,79300,Future Diary OVA,"Shounen, High Stakes Games, Play or Die, Psych...",4,0,0.0
20842174,8111,79300,Pokemon Sun & Moon,"Fantasy, Shounen, Elemental Powers, Family Fri...",6,0,0.0
20842189,6694,79300,JoJoâ€™s Bizarre Adventure: Stardust Crusaders -...,"Action, Adventure, Comedy, Shounen, Monster-of...",4,0,0.0
20842192,851,79300,BECK: Mongolian Chop Squad,"Drama, Shounen, Coming of Age, Lifestyle Chang...",4,0,0.0
20842195,1078,79300,Tengen Toppa Gurren Lagann,"Action, Adventure, Comedy, Mecha, Sci Fi, Comb...",4,0,0.0

In [73]:
data = data.loc[(data[['watching_status', 'watched_episodes', 'rating']] != 0).all(axis=1)]
data.shape
data

,anime_id,user_id,Name,Tags,watching_status,watched_episodes,rating
12,1061,1,Heroic Age,"Action, Adventure, Mecha, Sci Fi, Aliens, Mili...",5,1,2.5
28,2375,1,Mazinger Edition Z: The Impact!,"Action, Mecha, Sci Fi, Super Robot",3,1,2.0
36,2764,1,Chu-Bra!!,"Comedy, Ecchi, Seinen, Panty Shots, School Lif...",5,6,2.0
41,4683,1,Fate/Zero 2,"Action, Fantasy, Contemporary Fantasy, Magic, ...",2,11,4.5
43,1333,1,Sky Girls TV,"Sci Fi, Slice of Life, Military, Post-apocalyp...",2,6,3.0
...,...,...,...,...,...,...,...
20842079,8988,79300,Hakata Tonkotsu Ramens,"Mystery, Assassins, Criminals, Detectives, Gan...",3,1,3.5
20842099,8894,79300,Katana Maidens: Toji no Miko,"Action, Monsters, School Life, Supernatural, S...",3,2,3.0
20842113,8312,79300,Boruto: Naruto Next Generations,"Action, Fantasy, Shounen, Ninja, Based on a Manga",2,113,4.5
20842165,9540,79300,Today's Menu for Emiya Family,"Slice of Life, Cooking, Food and Beverage, Rec...",3,6,2.5
20842198,6646,79300,Shirobako,"Comedy, Drama, Slice of Life, Anime Industry, ...",3,2,3.0

In [74]:
data.describe()

,anime_id,user_id,watching_status,watched_episodes,rating
count,811860.000000,811860.000000,811860.000000,811860.000000,811860.000000
mean,4784.734484,39844.458521,3.165079,31.124836,3.173130
std,4058.677791,22964.352262,1.167819,108.908083,1.243848
min,2.000000,1.000000,2.000000,1.000000,0.500000
25%,1188.000000,19951.000000,2.000000,2.000000,2.500000
50%,3999.000000,40158.000000,3.000000,5.000000,3.500000
75%,7283.000000,59449.000000,5.000000,12.000000,4.000000
max,17114.000000,79300.000000,5.000000,2605.000000,5.000000

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 811860 entries, 12 to 20842198
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   anime_id          811860 non-null  int64
 1   user_id           811860 non-null  int64
 2   Name              811860 non-null  object
 3   Tags              811860 non-null  object
 4   watching_status   811860 non-null  int64
 5   watched_episodes  811860 non-null  int64
 6   rating            811860 non-null  float64
dtypes: float64(1), int64(4), object(2)
memory usage: 49.6+ MB

In [76]:
data.isnull().sum()

anime_id            0
user_id             0
Name                0
Tags                0
watching_status     0
watched_episodes    0
rating              0
dtype: int64

In [77]:
data.duplicated().sum()

0

In [78]:
data.to_csv('all_anime_clean.csv')

In [79]:
data_clean = pd.read_csv("all_anime_clean.csv")

In [80]:
data_clean

,Unnamed: 0,anime_id,user_id,Name,Tags,watching_status,watched_episodes,rating
0,12,1061,1,Heroic Age,"Action, Adventure, Mecha, Sci Fi, Aliens, Mili...",5,1,2.5
1,28,2375,1,Mazinger Edition Z: The Impact!,"Action, Mecha, Sci Fi, Super Robot",3,1,2.0
2,36,2764,1,Chu-Bra!!,"Comedy, Ecchi, Seinen, Panty Shots, School Lif...",5,6,2.0
3,41,4683,1,Fate/Zero 2,"Action, Fantasy, Contemporary Fantasy, Magic, ...",2,11,4.5
4,43,1333,1,Sky Girls TV,"Sci Fi, Slice of Life, Military, Post-apocalyp...",2,6,3.0
...,...,...,...,...,...,...,...,...
811855,20842079,8988,79300,Hakata Tonkotsu Ramens,"Mystery, Assassins, Criminals, Detectives, Gan...",3,1,3.5
811856,20842099,8894,79300,Katana Maidens: Toji no Miko,"Action, Monsters, School Life, Supernatural, S...",3,2,3.0
811857,20842113,8312,79300,Boruto: Naruto Next Generations,"Action, Fantasy, Shounen, Ninja, Based on a Manga",2,113,4.5
811858,20842165,9540,79300,Today's Menu for Emiya Family,"Slice of Life, Cooking, Food and Beverage, Rec...",3,6,2.5
811859,20842198,6646,79300,Shirobako,"Comedy, Drama, Slice of Life, Anime Industry, ...",3,2,3.0